server:
  port: 8081

spring:
  application:
    name: wooriBank

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      database: ${SPRING_DATA_REDIS_DATABASE:0}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jwt:
    secret: ${JWT_SECRET}
    access-expiration: 3600000
    refresh-expiration: 31536000000

auth:
  session:
    ttl: 300
  verification:
    ttl: 180
    max-attempts: 5

